# Generated by Django 5.1.3 on 2024-11-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], max_length=10)),
                ('job_position', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('Analyst', 'Analyst'), ('Tester', 'Tester'), ('Project Manager', 'Project Manager'), ('Software Engineer', 'Software Engineer'), ('Data Scientist', 'Data Scientist'), ('Data Analyst', 'Data Analyst'), ('Quality Assurance Engineer', 'Quality Assurance Engineer'), ('System Administrator', 'System Administrator'), ('DevOps Engineer', 'DevOps Engineer'), ('UI/UX Designer', 'UI/UX Designer'), ('Product Manager', 'Product Manager'), ('Sales Representative', 'Sales Representative'), ('Marketing Specialist', 'Marketing Specialist'), ('HR Manager', 'HR Manager'), ('Customer Support Specialist', 'Customer Support Specialist'), ('Technical Support Engineer', 'Technical Support Engineer'), ('IT Support Specialist', 'IT Support Specialist'), ('Content Writer', 'Content Writer'), ('SEO Specialist', 'SEO Specialist'), ('Finance Officer', 'Finance Officer'), ('Accountant', 'Accountant'), ('Operations Manager', 'Operations Manager'), ('Business Analyst', 'Business Analyst'), ('Network Engineer', 'Network Engineer'), ('Cybersecurity Specialist', 'Cybersecurity Specialist'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('AI Researcher', 'AI Researcher'), ('Database Administrator', 'Database Administrator')], max_length=50)),
                ('date_of_hire', models.DateField()),
                ('date_of_termination', models.DateField(blank=True, null=True)),
                ('department', models.CharField(choices=[('Management', 'Management'), ('Software Development', 'Software Development'), ('Design', 'Design'), ('Data Analysis', 'Data Analysis'), ('Quality Assurance', 'Quality Assurance'), ('Project Management', 'Project Management'), ('Engineering', 'Engineering'), ('Data Science', 'Data Science'), ('Systems Administration', 'Systems Administration'), ('DevOps', 'DevOps'), ('Product Management', 'Product Management'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Human Resources', 'Human Resources'), ('Customer Support', 'Customer Support'), ('Technical Support', 'Technical Support'), ('IT Support', 'IT Support'), ('Content Creation', 'Content Creation'), ('SEO', 'SEO'), ('Finance', 'Finance'), ('Accounting', 'Accounting'), ('Operations', 'Operations'), ('Business Analysis', 'Business Analysis'), ('Networking', 'Networking'), ('Cybersecurity', 'Cybersecurity'), ('Machine Learning', 'Machine Learning'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Database Administration', 'Database Administration')], max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Bi-Weekly', 'Bi-Weekly'), ('Weekly', 'Weekly')], max_length=10)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('emergency_contact_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Terminated', 'Terminated')], max_length=10)),
                ('previous_positions', models.TextField(blank=True, null=True)),
                ('performance_notes', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
