# Generated by Django 5.1.3 on 2024-11-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='performance_notes',
        ),
    ]
