# Generated by Django 5.1.3 on 2024-11-14 12:13

import Employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_employee_job_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(max_length=10, validators=[Employee.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[Employee.models.validate_phone_number]),
        ),
    ]
